env:

  CONFIG: setup.sh
  CIRRUS_SHELL: bash

task:
  name: "Evolution X - CI Build"
  timeout_in: 2500m
  container:
    image: ubuntu:20.04   # Use a specific version instead of "latest"
    cpu: 8
    memory: 20G


  Sync_Repo:
    - curl -sL https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/sync_repo.sh | bash

  Build_Rom:
    - curl -sL https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/build_rom.sh | bash

  Upload_Rom:
    - curl -sL https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/upload_rom.sh | bash
