env:
    CIRRUS_SHELL: bash

task:
  name: "Evolution X - System Image Builder"
  timeout_in: 3600m
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 20G

  Setup_script:
      - sudo apt install update
      - sudo apt install curl
      - curl -sL https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/setup.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/sync_repo.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/build_rom.sh | bash

  Upload_script:
      - curl https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/upload_rom.sh | bash
