name: Evolution X CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2500

    env:
      CIRRUS_SHELL: bash

    container:
      image: ubuntu:latest
      cpu: 32
      memory: 32G

    steps:
      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf libxml2 lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev imagemagick git lunzip lzop schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk python3 perl xmlstarlet virtualenv xz-utils rr jq libncurses5 pngcrush lib32ncurses5-dev git-lfs libxml2 openjdk-11-jdk-headless repo

      - name: Checking Disk Space
        run: df -h

      - name: Configure Git
        run: |
          git config --global user.name "your username"
          git config --global user.email yourmail@example.com

      - name: Sync Repo
        run: |
          curl -sL https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/sync_repo.sh | bash

      - name: Build ROM
        run: |
          curl -sL https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/build_rom.sh | bash

      - name: Upload ROM
        run: |
          curl -sL https://raw.githubusercontent.com/hoaggggggg/EvoBuild/main/upload_rom.sh | bash
